-- ─────────────────────────────────────────────────────────────────────────
-- TEMPORARY (legacy 5xxx migration): allow an explicit ro_number override.
--
-- WHY: We are draining legacy 5xxx repair orders off the v1 shop floor one
-- car at a time. An advisor needs to create a v2 RO that REUSES a car's
-- existing legacy PO (e.g. 5495) instead of getting the next auto-assigned
-- 6xxx number. `repair_orders.ro_number` is currently
-- `GENERATED ALWAYS AS IDENTITY`, which forbids inserting an explicit value
-- (Postgres error 428C9) — the PostgREST/anon client can't emit
-- `OVERRIDING SYSTEM VALUE`. Flipping it to `GENERATED BY DEFAULT` lets an
-- explicit value be inserted while the default path is UNCHANGED:
--   * omit ro_number  → the identity sequence still assigns the next 6xxx
--   * pass ro_number  → that value is used, and the sequence is NOT advanced
-- Every legacy value is < 6000 (the sequence's floor), so there is no
-- collision risk with future auto-assigned 6xxx numbers.
--
-- REMOVE AFTER MIGRATION: once all 5xxx cars are off the floor and the
-- override UI is deleted from advisor-board.html, you MAY flip this back to
-- `GENERATED ALWAYS` for extra safety:
--   alter table public.repair_orders
--     alter column ro_number set generated always;
-- (Leaving it BY DEFAULT is also harmless — the intake never sets ro_number
-- once the override markup is gone.)
--
-- Run this in the Supabase SQL Editor BEFORE the override UI is used.
-- ─────────────────────────────────────────────────────────────────────────

alter table public.repair_orders
  alter column ro_number set generated by default;

-- ── VERIFY (expect: is_identity = YES, identity_generation = BY DEFAULT) ──
-- select column_name, is_identity, identity_generation
--   from information_schema.columns
--  where table_schema = 'public'
--    and table_name   = 'repair_orders'
--    and column_name  = 'ro_number';
